import { test, expect } from './fixtures/launchPairedApp'

test('host rows have no dots at rest, hover or keyboard focus and retain Edit host', async ({ launchPairedApp }, testInfo) => {
  const { page } = await launchPairedApp()
  const host = page.locator('.channel-list__host')
  const disclosure = host.locator('.channel-list__host-disclosure')
  const edit = host.getByRole('button', { name: 'Edit host' })
  const dots = host.locator('.channel-list__host-status, .channel-list__host-dot')
  await expect(host).toHaveCount(1)
  await expect(edit).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Add workspace' })).toHaveCount(0)
  await page.mouse.move(700, 400)
  await expect(edit).toHaveCSS('opacity', '0')
  await expect(dots).toHaveCount(0)
  const rowBox = await host.boundingBox()
  const disclosureBox = await disclosure.boundingBox()
  const editBox = await edit.boundingBox()
  expect(rowBox?.height).toBe(28)
  if (!rowBox || !disclosureBox || !editBox) throw new Error('host controls must have layout boxes')
  expect(disclosureBox.x + disclosureBox.width).toBeLessThanOrEqual(editBox.x)
  expect(rowBox.x + rowBox.width - editBox.x - editBox.width).toBe(25)
  await page.screenshot({ path: testInfo.outputPath('host-rest.png'), animations: 'disabled' })

  await host.hover()
  await expect(edit).toHaveCSS('opacity', '1')
  await expect(dots).toHaveCount(0)
  expect(await host.boundingBox()).toEqual(rowBox)
  expect(await disclosure.boundingBox()).toEqual(disclosureBox)
  expect(await edit.boundingBox()).toEqual(editBox)
  await page.screenshot({ path: testInfo.outputPath('host-hover.png'), animations: 'disabled' })
  await edit.click()
  const dialog = page.getByRole('dialog', { name: 'Edit host' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()

  // Tab from the native disclosure to the sibling pen with the pointer outside the row.
  await page.mouse.move(700, 400)
  await disclosure.focus()
  await page.keyboard.press('Tab')
  await expect(edit).toBeFocused()
  await expect(edit).toHaveCSS('opacity', '1')
  await expect(edit.locator('.channel-list__control-name')).toBeVisible()
  await expect(dots).toHaveCount(0)
  expect(await host.boundingBox()).toEqual(rowBox)
  expect(await edit.boundingBox()).toEqual(editBox)
  await page.keyboard.press('Enter')
  await expect(dialog).toBeVisible()
})
