import { test, expect } from './fixtures/launchPairedApp'

test('Edit host keeps its pointer name pill without a host Add workspace control', async ({ launchPairedApp }) => {
  const { page } = await launchPairedApp()
  const host = page.locator('.channel-list__host')
  const edit = host.getByRole('button', { name: 'Edit host' })
  const pill = edit.locator('.channel-list__control-name')
  await expect(host).toHaveCount(1)
  await expect(edit).toHaveCount(1)
  await expect(page.locator('.channel-list__host-add')).toHaveCount(0)
  await expect(pill).toHaveCSS('display', 'none')
  await edit.hover()
  await expect(pill).toHaveCSS('display', 'block')
  await expect(pill).toHaveText('Edit host')
  const control = await edit.boundingBox()
  expect(control).not.toBeNull()
  const before = await pill.boundingBox()
  if (control === null) throw new Error('Edit host has no layout box')
  await page.mouse.move(control.x + 4, control.y + 4)
  const after = await pill.boundingBox()
  expect(before).not.toBeNull()
  expect(after).not.toBeNull()
  expect(after?.x).not.toBe(before?.x)
})
